### ISSUE TITLE
Add bare metal baseline?

### ISSUE THREAD

**Issue by rothgar** [dkechag/Benchmark-DKbench#1]
I was reading your [great blog post](https://dev.to/dkechag/cloud-vm-performance-value-comparison-2023-perl-more-1kpp) about comparing cloud performance and I was wondering if you'd be interested in adding some baseline performance numbers for bare metal. 

I know price might be a little more tricky to compare price, but if I were able to provide some performance numbers on multiple off the shelf systems (something you could compare MSRP price) would you be interested?

If you need to add price comparison I thought you could divide the MSRP by 3 and compare it to the 3 year reserved prices.

**Comment by dkechag** [comment]
Hi. That's not a bad idea at all, although it would be interesting as a standalone comparison - I think the VM cloud comparison is already complex, I was trying to avoid more complexity. E.g. in my [2022 comparison](https://blogs.perl.org/users/dimitrios_kechagias/2022/03/cloud-provider-performance-comparison-gcp-aws-azure-perl.html), I had included Apple Silicon & Mobile CPUs, to get a better idea of what kind of performance we are talking about, but it became a bit much I thought. And bare-metal servers would probably be a more useful comparison, especially for people who are debating colocation vs cloud. But, again, it's kind of a different question than the one I was trying to answer. However, if you'd like to do a writeup, you are free to use my numbers for comparison (there's a link with the raw numbers on the blog post) - a link to the source is enough. I could also perhaps do a quick write-up instead using your numbers, but I see you already blog, so you might want to do it.
