### ISSUE TITLE
Failures on Math::MatrixReal

### ISSUE THREAD

**Issue by otheus** [dkechag/Benchmark-DKbench#2]
How to resolve the following, please?

```
--------------- Software ---------------
DKbench v2.4
Perl v5.16.3 (threads, multi)
OS: Red Hat Enterprise Linux Server 7.9 (Maipo)
--------------- Hardware ---------------
CPU type: AMD EPYC 7402 24-Core Processor (x86_64)
CPUs: 24 (24 Cores)
----------------------------------------
DKbench single-thread run:
Benchmark           Score               Pass/Fail
Math::MatrixReal:     319               Fail (8548e0d817a4674dca01e5f2e3f372e4)
Overall Score:        319
----------------------------------------
```

The `setup_dkbench` ran successfully without errors.
All other tests ran without failures.

```
~$ cpanm Math::MatrixReal
Math::MatrixReal is up to date. (2.13)
```

**Comment by dkechag** [comment]
Hello. The "Fail" is only worrying if you are on the recommended Perl version (5.36), which you are not. The short answer is to not worry about a checksum mismatch on older Perl or library versions - the benchmark does warn about it.

**Comment by dkechag** [comment]
@otheus I will close this as it is as designed, but feel free to open any other issue, or if you want more info on this particular behaviour, you can email me (address on the README). Thanks!
